INSERT INTO public.property_name (id, name, is_size) VALUES (4, 'L, мм', true);
INSERT INTO public.property_name (id, name, is_size) VALUES (5, 'B, мм', true);
INSERT INTO public.property_name (id, name, is_size) VALUES (6, 'H, мм', true);
INSERT INTO public.property_name (id, name, is_size) VALUES (7, 'L1, мм', true);
INSERT INTO public.property_name (id, name, is_size) VALUES (8, 'L2, мм', true);
INSERT INTO public.property_name (id, name, is_size) VALUES (9, 'L3, мм', true);
INSERT INTO public.property_name (id, name, is_size) VALUES (10, 'L4, мм', true);
INSERT INTO public.property_name (id, name, is_size) VALUES (11, 'B1, мм', true);
INSERT INTO public.property_name (id, name, is_size) VALUES (12, 'B2, мм', true);
INSERT INTO public.property_name (id, name, is_size) VALUES (13, 'H1, мм', true);
INSERT INTO public.property_name (id, name, is_size) VALUES (14, 'H2, мм', true);
INSERT INTO public.property_name (id, name, is_size) VALUES (15, 'H3, мм', true);
INSERT INTO public.property_name (id, name, is_size) VALUES (16, 'D1', true);
INSERT INTO public.property_name (id, name, is_size) VALUES (17, 'D2', true);
INSERT INTO public.property_name (id, name, is_size) VALUES (18, 'D3, мм', true);
INSERT INTO public.property_name (id, name, is_size) VALUES (19, 'Марка котла', false);
INSERT INTO public.property_name (id, name, is_size) VALUES (20, 'Вид топлива', false);
INSERT INTO public.property_name (id, name, is_size) VALUES (21, 'Номинальная тепловая мощность', false);
INSERT INTO public.property_name (id, name, is_size) VALUES (22, 'Отапливаемая площадь, (при высоте помещения 3м)', false);
INSERT INTO public.property_name (id, name, is_size) VALUES (23, 'КПД', false);
INSERT INTO public.property_name (id, name, is_size) VALUES (24, 'Номинальный расход', false);
INSERT INTO public.property_name (id, name, is_size) VALUES (25, 'Присоединительная резьба', false);
INSERT INTO public.property_name (id, name, is_size) VALUES (26, 'Размеры дымохода ∅ мм	', false);
INSERT INTO public.property_name (id, name, is_size) VALUES (27, 'Масса, не более кг', false);
INSERT INTO public.property_name (id, name, is_size) VALUES (28, 'Напряжение питания, В', false);
INSERT INTO public.property_name (id, name, is_size) VALUES (29, 'Потребляемая мощность, Вт', false);
INSERT INTO public.property_name (id, name, is_size) VALUES (30, 'Марка газового клапана', false);
INSERT INTO public.property_name (id, name, is_size) VALUES (31, 'Давление газа перед котлом при работе на природном газе / на сжи', false);
INSERT INTO public.property_name (id, name, is_size) VALUES (32, 'D4', true);
INSERT INTO public.property_name (id, name, is_size) VALUES (33, 'B', true);
INSERT INTO public.property_name (id, name, is_size) VALUES (34, 'H', true);
INSERT INTO public.property_name (id, name, is_size) VALUES (35, 'Hmax', true);
INSERT INTO public.property_name (id, name, is_size) VALUES (36, 'Максимальная температура воды на выходе, °C', false);
INSERT INTO public.property_name (id, name, is_size) VALUES (38, 'Вес котла (без воды), т', false);
INSERT INTO public.property_name (id, name, is_size) VALUES (39, 'Газопровод, мм', true);
INSERT INTO public.property_name (id, name, is_size) VALUES (40, 'Дымоход, мм', true);
INSERT INTO public.property_name (id, name, is_size) VALUES (41, 'Воздушно-приточная щель, см2', true);
INSERT INTO public.property_name (id, name, is_size) VALUES (42, 'Трубопровод подающий, мм', true);
INSERT INTO public.property_name (id, name, is_size) VALUES (43, 'Трубопровод обратный, мм', true);
INSERT INTO public.property_name (id, name, is_size) VALUES (44, 'Газовая свеча, мм', true);
INSERT INTO public.property_name (id, name, is_size) VALUES (45, 'Дренаж котла, мм', true);
INSERT INTO public.property_name (id, name, is_size) VALUES (46, 'Сброс предох. клапана, мм', true);
INSERT INTO public.property_name (id, name, is_size) VALUES (47, 'ширина, мм', true);
INSERT INTO public.property_name (id, name, is_size) VALUES (48, 'глубина, мм', true);
INSERT INTO public.property_name (id, name, is_size) VALUES (49, 'высота, мм', true);
INSERT INTO public.property_name (id, name, is_size) VALUES (50, 'L5', true);
INSERT INTO public.property_name (id, name, is_size) VALUES (51, 'L6', true);
INSERT INTO public.property_name (id, name, is_size) VALUES (52, 'Максимальный расход сжиженного газа кг/час', false);
INSERT INTO public.property_name (id, name, is_size) VALUES (53, 'Давление газа, кПа', false);
INSERT INTO public.property_name (id, name, is_size) VALUES (54, 'Максимальная тепловая мощность на природном/сжиженном газе, кВт	', false);
INSERT INTO public.property_name (id, name, is_size) VALUES (55, 'Используемое топливо', false);
INSERT INTO public.property_name (id, name, is_size) VALUES (56, 'Теплопроизводительность номинальная, кВт', false);
INSERT INTO public.property_name (id, name, is_size) VALUES (57, 'Объем отапливаемого помещения, м³', false);
INSERT INTO public.property_name (id, name, is_size) VALUES (58, 'Диаметр дымохода наружний, мм', false);
INSERT INTO public.property_name (id, name, is_size) VALUES (59, 'Объем загружаемых камней, дм³', false);
INSERT INTO public.property_name (id, name, is_size) VALUES (60, 'Габаритные размеры в сборе, мм, не более', false);